### ISSUE TITLE
Potentially too many PE and DVT events

### ISSUE THREAD

**Issue by venexia** [opensafely/post-covid-vaccinated#122]
Approximately 14.6m people in the vaccinated cohort, i.e., about 30% of those in the NHSD TRE analysis. 

In the NHSD TRE analysis, we observed 32,153 pulmonary embolism cases so anticipate ~9600 in the vaccinated cohort but we have almost double that.

Similarly, in the NHSD TRE analysis, we observed 25,590 deep vein thrombosis cases so anticipate ~7600 in the vaccinated cohort but we have nearly three times that number.

Both pulmonary embolism and deep vein thrombosis contribute to the combined outcome 'venous thromboembolism events' so naturally that is also much higher in the vaccinated cohort than we would expect from our NHSD TRE work.

Perhaps we need to check the codelists to ensure they are comparable? Similar issue for deep vein thrombosis in the unvaccinated cohort, seems to be less of a problem for pulmonary embolism  there.

**Comment by rdenholm** [comment]
Investigated and cant find any reason for it, so we're happy with the numbers
