### ISSUE TITLE
date of measurements for covariates

### ISSUE THREAD

**Issue by yinghuiwei** [opensafely/post-covid-vaccinated#209]
I see there has been some inconsistency in the time period where covariates are defined, some are at index date variable (defined baseline for the relevant population), but some are up to "today":

https://github.com/opensafely/post-covid-vaccinated/blob/main/analysis/common_variables.py#L2172-L2209

**Comment by GenevieveCezard** [comment]
This has been addressed in `common_variables.py` as expected in the following PR: https://github.com/opensafely/post-covid-vaccinated/pull/214
